### PR TITLE
Fixed console multiline behavior

### PR DESCRIPTION
**Pull request by KidFashion**
Fixed the annoying behavior of booish.exe when a command spills on multiple line, i've tested it with delete, history, autocompletion, indent, key arrows and insert.

### CODE REVIEW

**Comment by KidFashion** [comment]
Build is actually failing because 2 test are failing, they seems not related with the PR because i've noticed that also [master](https://travis-ci.org/boo-lang/boo/builds/123619967), is failing for the same reason.

**Comment by masonwheeler** [comment]
This looks very nice, and it's something booish has sorely needed for a long time.  I can't test it now, but I'll check this when I get home this evening and if it works, I'll merge it. :)

**Comment by masonwheeler** [comment]
This works really well, except that if you go beyond one line, the `Home` and `End` keys stop working as expected.  `Home` returns the cursor to the home X position on the current vertical row, rather than the beginning of the wrapped-around line, and `End` raises an unhandled exception.

Can you look into this?  If those two keys were fixed, this would be ready to merge. :)

**Comment by KidFashion** [comment]
Ok i should have fixed Home & End key behaviors, it's still failing the build for the aforementioned two tests but it works on my machine, I did an extra-commit to clean csproj files that were changed (probably by my VS), now the pull request is correctly reporting changing just 1 file (InteractiveInterpreterConsole.boo).

Make me know if it works as intended...

**Comment by masonwheeler** [comment]
These changes look good.  I've noticed one other minor problem, but it's small enough that it's not worth delaying the merge for.

If I write a statement and press `ENTER`, Booish will print the result on the next line.  However, if I write a multiline statement, press `HOME`, and then press `ENTER`, Booish will print the result on the next line down from the current cursor position, partially overwriting what I typed in the second line, rather than printing the result on the line after the end of the multiline statement.

Can you come up with a PR to fix this?

Merging and closing this PR now, because it doesn't seem like that's a scenario that is likely to happen very often.

**Pull request merged**
