### PR TITLE
Boo.Lang ported to DNXCORE

### PR DESCRIPTION
**Pull request by watsug**

### CODE REVIEW

**Comment by masonwheeler** [comment]
Hey, thanks for the PR!  This looks really good; just a couple notes:

 - In several places you added a new `using` clause to include namespaces that are only used inside conditional code.  Can you make those `using` clauses conditional too?

 - workspace.xml is massive and appears to be composed mostly of historical data.  Is there any way to clean that up a little?

Having Boo run on .NET Core would be great, and this looks like an important first step.  Thanks for putting in the effort to get the ball rolling on this! 😀

**Comment by watsug** [comment]
Hi,
Sure, I'll fix it today.

**Comment by masonwheeler** [comment]
Awesome, thanks!

**Comment by watsug** [comment]
Hi, I did the changes but it is still failing. Do you have an idea why? I am not also sure, but seems to me that after compilation in VS some other files have been regenerated...

**Comment by masonwheeler** [comment]
The conditionals look good, but why did you change the parser?

Don't worry about the failing tests; the build machine's test runner is b0rked.

**Comment by watsug** [comment]
Hi,

I didn't do anything special. I just executed nant and I think this is the reason. Should I remove these changes? I am not sure. Why executing nant changed the parser. Was it regenerated properly before?

**Comment by masonwheeler** [comment]
Yeah.  As a general rule of thumb, if you don't know why a change is there and it had nothing to do with what you were working on, you'd be better off reverting it rather than committing it.  It looks like this changes the semantics of the parser in at least one case.

**Comment by masonwheeler** [comment]
All right, that latest looks good.  Merging. 😃

**Comment by masonwheeler** [comment]
Also, feel free to drop by [the Boo dev group](https://groups.google.com/forum/#!forum/boolang) and talk about your work on this.

**Pull request merged**
