### PR TITLE
Bootstrap for bash

### PR DESCRIPTION
**Pull request by eatdrinksleepcode**

### CODE REVIEW

**Comment by eatdrinksleepcode** [comment]
Please hold off on merging while I iron a few thing with the Travis build. I will see if there is a way for me to test the build without opening a PR...

**Comment by masonwheeler** [comment]
All right.  It looks like this is running the Travis tests, and I think it'll re-run them when you update with a new commit, so that should help a lot.

**Comment by eatdrinksleepcode** [comment]
OK, I was able to use a Travis build on my fork to work through all of the messy trial and error, and I think we are in a good state now.

Next up will be a Windows/.NET version of the same bootstrap process.

**Comment by masonwheeler** [comment]
All right!  Hope this works! 😁

**Pull request merged**
