### PR TITLE
Use runtime dispatching for argument exploding

### PR DESCRIPTION
**Pull request by drslump**
Currently Boo does only allow the following use of the explode arguments operator:

    def bar(a, *args)  
    # bar(1, *(2, 3)) 

The following changes allow to have a more powerful exploding operator which works like the one in Python. The drawback is that it uses the runtime to actually dispatch the call, with a bit more work the original use case supported by Boo could bypass the runtime dependency but it's not worth the effort IMHO.

    def foo(a, b, c)
    # foo(1, *(2, 3))
    def bar(a, *args)
    # bar(1, *(2, 3))
    # bar(*(1, 2, 3))
    # bar(1, 2, *(3,))
    # bar(1, 2, 3)

NOTE: No unit tests yet, I'll provide them if you think this could actually be merged. :octocat:

### CODE REVIEW

**Comment by bamboo** [comment]
Thanks!

**Comment by bamboo** [comment]
@drslump, would you care to investigate the build failure caused by this PR and resubmit it?

https://travis-ci.org/boo-lang/boo/builds/97956507

**Comment by drslump** [comment]
@bamboo sure, I´m testing on Mono 4.2 on windows and the test passes, downloading 3.12 to verify what went wrong on CI... I'll also take the change to add some unit tests for the new behaviour

**Comment by bamboo** [comment]
Great!

**Pull request merged**
